server:
  port: 9090

spring:
  application:
    name: core-bank
  data:
    mongodb:
#      uri: mongodb+srv://zuhlke01:f10zuhlke@zuhlke-0-pcykf.gcp.mongodb.net/core-bank?retryWrites=true
      uri: mongodb://zuhlke01:f10zuhlke@mongodb-container:27017/core-bank

