version: '3'
services:
 bank-api:
  image: zuhlke/bank-api:dev
  ports:
    - "9090:9090"
 account-api:
  image: zuhlke/account-api:dev
  ports:
    - "9091:9091"
 transaction-api:
  image: zuhlke/transaction-api:dev
  ports:
    - "9092:9092"
