swagger: '2.0'
info:
  version: ''
  title: core-bank
  description: ''
host: 'localhost:3000'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  API-KEY:
    name: API-KEY
    type: apiKey
    in: header
paths:
  '/accounts/{id}/transactions':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET_accounts-id-transactions
      summary: Get Transactions
      tags:
        - Transactions
      description: Retrieve transaction history of an account
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/account-transactions'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - API-KEY: []
    post:
      operationId: POST_accounts-id-transactions
      summary: Create Transaction
      tags:
        - Transactions
      description: Create a Debit or Credit transaction for an account
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/transaction'
            example:
              id: dolor irure consequat tempor dolore
              transaction_reference: sit dolore ad cillum proident
              currency: enim incididunt
              amount: qui
              credit_debit_indicator: Credit
              booking_date_time: '5108-03-12T06:49:45.650Z'
              value_date_time: '4511-04-01T17:21:58.613Z'
              transaction_code: deserunt ut commodo in
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/transfer-response'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
      security:
        - Authorization: []
        - API-KEY: []
  '/accounts/{id}/transfer':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    post:
      operationId: POST_accounts-id-transfer
      summary: Transfer Fund
      tags:
        - Transfers
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/fund-transfer-detail'
            example:
              fund_transfer_detl:
                debit_account_id: consectetur sint
                credit_account_number: et
                bank_code: ad mollit cupidatat commodo
                payee_name: elit ea officia consectetur eiusmod
                payment_channel: voluptate sint
                amount: exercitation non
                source_currency: irure ad esse
                destination_currency: eiusmod velit
                transfer_currency: irure sint dolor enim magna
                comments: Lorem anim ullamco
                purpose: deserunt Excepteur laborum
                transfer_type: INSTANT
                value_date: '2274-10-16'
                party_id: voluptate e
                reference_id: pariatur aute anim
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/transfer-response'
          examples:
            application/json:
              reference_id: enim ipsum
              status: ACCEPTED
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - API-KEY: []
  '/accounts/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET-account
      summary: Get account details
      tags:
        - Accounts
      description: Get account details including the balance
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/account-balance'
          examples:
            application/json:
              id: anim aliquip
              bank_code: sit
              account_number: labore reprehenderit
              name: sint esse adipisicing Excepteur
              balance: 500
              currency: SGD
              product_type: ullamco
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
          examples:
            application/json:
              code: sint ea consectetur occaecat est
              message: ea dolor consectetur commodo
              tracking_id: dolor
      security:
        - Authorization: []
        - API-KEY: []
    put:
      operationId: PUT-account
      summary: Update account
      tags:
        - Accounts
      description: Update an existing bank account
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/account'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/account'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - API-KEY: []
    delete:
      operationId: DELETE-account
      summary: Delete account
      tags:
        - Accounts
      description: Delete an existing bank account
      responses:
        '204':
          description: ''
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - API-KEY: []
  /accounts:
    get:
      operationId: LIST-accounts
      summary: List accounts
      tags:
        - Accounts
      description: Retrieve the list of bank accounts
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/account'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - API-KEY: []
    post:
      operationId: POST-account
      summary: Create account
      tags:
        - Accounts
      description: Create a new bank account
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/account'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/account'
          examples:
            application/json:
              id: deserunt
              bank_code: aute
              account_number: ut pariatur nostrud veni
              name: non exercitation ut dolor
              currency: minim ut ullamco
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - API-KEY: []
definitions:
  generic-error:
    title: generic-error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
  server-error:
    title: server-error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      tracking_id:
        type: string
  account:
    title: Account
    type: object
    properties:
      id:
        type: string
        description: Tokenised Account Identifier
      bank_code:
        type: string
        description: Bank code of the payee's bank. ACH code for domestic banks / SWIFT code for overseas bank.
      account_number:
        type: string
        description: account number
      name:
        type: string
        description: Name of the owner
      currency:
        type: string
        description: Currency of the account
      product_type:
        type: string
        description: Product Type
    example:
      id: in voluptate sint velit
      bank_code: proident qui
      account_number: eiusmod
      name: cillum eu culpa laborum
      currency: eu sit ut et officia
  fund-transfer-detail:
    title: Fund Transfer Detail
    type: object
    properties:
      credit_account_number:
        type: string
        description: Account number of the payee
      bank_code:
        type: string
        description: Bank code of the payee's bank. ACH code for domestic banks / SWIFT code for overseas bank.
      payee_name:
        type: string
        description: Payee name
      amount:
        type: number
        description: 'Amount of money to be transferred to the payee '
      source_currency:
        type: string
        description: 'Currency of the payer''s bank account '
      destination_currency:
        type: string
        description: Currency of the payee's bank account
      transfer_currency:
        type: string
        description: Transfer Currency. Should be either Debit or Credit account's currency
      comments:
        type: string
        description: Short comment about the transaction
      transfer_type:
        type: string
        enum:
          - INSTANT
          - NON-INSTANT
        description: 'Type of transfer: INTANT or NON-INSTANT'
      value_date:
        type: string
        format: date
        description: 'Date on which fund has to be settled. Can be a future date. Default: current date'
      reference_id:
        type: string
        description: Transaction Reference number for transfers and payments
  transfer-response:
    title: Transfer Response
    type: object
    properties:
      reference_id:
        type: string
        description: Transaction Id
      status:
        type: string
        enum:
          - ACCEPTED
          - REJECTED
        description: Transaction Status
      comment:
        type: string
        description: Short comment about the transaction
  account-transactions:
    title: Account Transactions
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/transaction'
    example:
      data:
        - value_date_time: '3154-09-28T20:03:15.214Z'
          currency: in n
          booking_date_time: '3390-05-03T20:18:51.770Z'
          transaction_reference: ex dese
        - credit_debit_indicator: Debit
          transaction_id: occaecat ut qui aute
          transaction_reference: tempor
          booking_date_time: '2866-05-05T05:13:13.378Z'
          currency: non
          value_date_time: '3670-10-22T09:56:27.846Z'
        - {}
        - {}
  account-balance:
    title: Account Balance
    type: object
    properties:
      id:
        type: string
        description: Tokenised Account Identifier
      bank_code:
        type: string
        description: Bank code of the payee's bank. ACH code for domestic banks / SWIFT code for overseas bank.
      account_number:
        type: string
        description: Account number
      name:
        type: string
        description: Name of the owner
      balance:
        type: number
        description: Account balance
      currency:
        type: string
        description: Currency of the account
      product_type:
        type: string
        description: Product Type
  transaction:
    title: Transaction
    type: object
    properties:
      id:
        type: string
        description: Transaction Id
      account_id:
        type: string
        description: Account Id
      transaction_reference:
        type: string
        description: Transaction Reference
      currency:
        type: string
        description: Transaction Currency
      amount:
        type: number
        description: Transaction amount
      credit_debit_indicator:
        type: string
        enum:
          - Credit
          - Debit
        description: Credit/Debit Indicator
      booking_date_time:
        type: string
        description: Booking Datetime
        format: date-time
      value_date_time:
        type: string
        description: Value Datetime
        format: date-time
      transaction_code:
        type: string
        description: Transaction Code