swagger: '2.0'
info:
  version: '1.0'
  title: Crowd Funding
  description: API Suite for Crowd Funding
host: 'localhost:8080'
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  X-API-KEY:
    name: X-API-KEY
    type: apiKey
    in: header
paths:
  '/campaigns/{campaign_id}':
    parameters:
      - name: campaign_id
        in: path
        required: true
        type: string
        description: Id of the campaign to get the details
    get:
      operationId: get-campaign
      summary: Get Campaign
      tags:
        - Campaigns
      responses:
        '200':
          description: 'Successful Response'
          schema:
            $ref: '#/definitions/campaign-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    put:
      operationId: update-campaign
      summary: Update Campaign
      tags:
        - Campaigns
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/campaign'
      responses:
        '200':
          description: 'Successful Response'
          schema:
            $ref: '#/definitions/campaign-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    delete:
      operationId: delete-campaign
      summary: Delete Campaign
      tags:
        - Campaigns
      responses:
        '204':
          description: 'Successfully Deleted'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  /campaigns:
    get:
      operationId: LIST-campaigns
      summary: List Campaigns
      tags:
        - Campaigns
      parameters:
        - name: name
          in: query
          description: Name of the Campaign
          type: string
        - name: status
          in: query
          type: string
          enum:
            - OPEN
            - CLOSED
        - name: category
          in: query
          type: string
        - name: sort
          in: query
          description: 'Fields to sort the response in ascending or descending order. To sort in descending order, select the field with "-" as prefix'
          type: array
          enum:
            - NAME
            - TARGET_AMOUNT
            - CREATED_DATE
            - '-NAME'
            - '-TARGET_AMOUNT'
            - '-CREATED_DATE'
          items:
            type: string
      responses:
        '200':
          description: 'Successful Response'
          schema:
            type: array
            items:
              $ref: '#/definitions/campaign-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    post:
      operationId: create-campaign
      summary: Create Campaign
      tags:
        - Campaigns
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/campaign'
      responses:
        '201':
          description: 'Successfully Created'
          schema:
            $ref: '#/definitions/campaign-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  '/campaigns/{campaign_id}/contributors':
    parameters:
      - name: campaign_id
        in: path
        required: true
        type: string
    get:
      operationId: list-contributors
      summary: List Campaign Contributors
      tags:
        - Contributors
      responses:
        '200':
          description: 'Successful Response'
          schema:
            type: array
            items:
              $ref: '#/definitions/contributor-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    post:
      operationId: register-contributor
      summary: Register As Contributor
      tags:
        - Contributors
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/contributor'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/contributor-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  '/campaigns/{campaign_id}/contributors/{contributor_id}':
    parameters:
      - name: campaign_id
        in: path
        required: true
        type: string
      - name: contributor_id
        in: path
        required: true
        type: string
    put:
      operationId: update-contributor
      summary: Update Contributor Details
      tags:
        - Contributors
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/contributor'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/contributor-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    delete:
      operationId: delete-contributor
      summary: Delete Contributor
      tags:
        - Contributors
      responses:
        '204':
          description: 'Succesfully Deleted'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  '/campaigns/{campaign_id}/contributors/{contributor_id}/contributions':
    parameters:
      - name: campaign_id
        in: path
        required: true
        type: string
      - name: contributor_id
        in: path
        required: true
        type: string
    post:
      operationId: add-contribution-details
      summary: Add Contribution details
      tags:
        - Contributors
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/contribution'
      responses:
        '201':
          description: 'Successfully added contribution details'
          schema:
            $ref: '#/definitions/contribution-info'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: 'Resource Not Found'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
definitions:
  campaign:
    title: Campaign
    type: object
    properties:
      name:
        type: string
        description: Name of the campaign
      description:
        type: string
        description: Brief description about the campaign
      website_url:
        type: string
        description: Url of the website if available for the campaign to provide more details for the contributors
      target_amount:
        type: number
        description: Minimum amount required to raise from the campaign
      raised_amount:
        type: number
        description: current value of the amount raised from the campaign so far.
      currency:
        type: string
        description: currency in which amount is raised/provided.
      category:
        type: string
        description: Field to provide information about which category, the campaign belongs to. for eg, personal or business ..etc
      status:
        type: string
        enum:
          - OPEN
          - CLOSED
        description: status of the campaign. status will be OPEN initially and changed to CLOSED once the required amount is raised from the campaign
      created_date:
        type: string
        format: date
      start_date:
        type: string
        format: date
        description: Date on which campaign is created in the system.
      end_date:
        type: string
        format: date
        description: Projected end date or date by which campaign should raise the target amount.
      account-details:
        $ref: '#/definitions/campaign-account'
      organizers:
        type: array
        items:
          $ref: '#/definitions/person'
        description: Details of the organizers.
  campaign-info:
    title: 'Campaign Details with ID'
    type: object
    properties:
      id:
        type: string
        description: ID of the campaign.
      campaign:
        $ref: '#/definitions/campaign'
  person:
    title: Person
    type: object
    properties:
      name:
        type: string
        description: Name of the Organizer.
      email:
        type: string
        description: Email of the Organizer.
  server-error:
    title: Server Error
    type: object
    properties:
      code:
        type: string
        description: Error code.
      message:
        type: string
        description: Reason for the error .
      tracking_id:
        type: string
        description: Tracking Id of the error which can be used to troubleshoot further.
  generic-error:
    title: Generic Error
    type: object
    properties:
      code:
        type: string
        description: Error code.
      message:
        type: string
        description: Reason for the error .
  campaign-account:
    title: Campaign Account Details
    type: object
    properties:
      bank_name:
        type: string
        description: Name of the Bank.
      bank_swift_code:
        type: string
        description: Swift code of the bank.
      account_number:
        type: string
        description: Account number.
      account_name:
        type: string
        description: Name of the account owner.
  contributor:
    title: Contributor
    type: object
    properties:
      name:
        type: string
        description: Name of the Contributor.
      email:
        type: string
        description: Email of the Contributor.
      phone_number:
        type: string
        description: Phone Number of the contributor.
      address:
        type: string
        description: Address of the contributor.
      amount:
        type: number
        description: Amount contributed to the campaign so far.
      currency:
        type: string
        description: currency of the amount contributed.
      contribution_date:
        type: string
        format: date
        description: Date on which the last contribution is made.
  contributor-info:
    title: Contributor
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the contributor.
      campaign_id:
        type: string
        description: Unique ID of the campaign.
      contributor:
        $ref: '#/definitions/contributor'
  contribution:
    title: Contribution Details
    type: object
    properties:
      amount:
        type: number
        description: Amount contributed to the campaign .
      currency:
        type: string
        description: Currency of the amount contributed .
      payment_transaction_id:
        type: string
        description: Transaction ID of the payment or contribution to the campaign .
      payment_date:
        type: string
        description: Date of the payment.
  contribution-info:
    title: Contribution Details with ID
    type: object
    properties:
      id:
        type: string
        description: Unique ID of the contribution.
      contributor_id:
        type: string
        description: ID of the contributor .
      campaign_id:
        type: string
        description: ID of the campaign.
      contribution:
        $ref: '#/definitions/contribution'
