swagger: '2.0'
info:
  version: ''
  title: Digital Lending
  description: API Suite for Digital Lending platforms
host: 'localhost:8080'
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  X-API-KEY:
    name: X-API-KEY
    type: apiKey
    in: header
paths:
  '/loans/{loan_id}':
    parameters:
      - name: loan_id
        in: path
        required: true
        type: string
    get:
      operationId: get-loan
      summary: Get Loan
      tags:
        - Loans
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/loan'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    put:
      operationId: update-loan
      summary: Update Loan
      tags:
        - Loans
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/loan'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/loan'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    delete:
      operationId: delete-loan
      summary: Delete Loan
      tags:
        - Loans
      responses:
        '204':
          description: ''
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  /loans:
    get:
      operationId: list-loans
      summary: List Loans
      tags:
        - Loans
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/list-loan-response'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    post:
      operationId: create-loan
      summary: Create Loan
      tags:
        - Loans
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/loan'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/loan'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  '/borrowers/{borrower_id}':
    parameters:
      - name: borrower_id
        in: path
        required: true
        type: string
    get:
      operationId: get-borrower
      summary: Get Borrower
      tags:
        - Borrowers
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/borrower'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    put:
      operationId: update-borrower
      summary: Update Borrower
      tags:
        - Borrowers
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/borrower'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/borrower'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    delete:
      operationId: delete-borrower
      summary: Delete Borrower
      tags:
        - Borrowers
      responses:
        '204':
          description: ''
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  /borrowers:
    get:
      operationId: list-borrowers
      summary: List Borrowers
      tags:
        - Borrowers
      responses:
        '200':
          description: 'Successful Response'
          schema:
            $ref: '#/definitions/list-borrower-response'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    post:
      operationId: create-borrower
      summary: Create Borrower
      tags:
        - Borrowers
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/borrower'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/borrower'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
  '/investors/{investor_id}':
    parameters:
      - name: investor_id
        in: path
        required: true
        type: string
    get:
      operationId: get-investor
      summary: Get Investor
      tags:
        - Investors
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/investor'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    put:
      operationId: Update-investor
      summary: Update Investor
      tags:
        - Investors
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/investor'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/investor'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    delete:
      operationId: delete-investor
      summary: Delete Investor
      tags:
        - Investors
      responses:
        '204':
          description: 'Successfully Deleted'
      security:
        - Authorization: []
        - X-API-KEY: []
  /investors:
    get:
      operationId: list-investors
      summary: List Investors
      tags:
        - Investors
      responses:
        '200':
          description: 'Successful Response'
          schema:
            $ref: '#/definitions/list-investor-response'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
    post:
      operationId: create-investor
      summary: Create Investor
      tags:
        - Investors
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/investor'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/investor'
        '401':
          description: 'Authentication Error'
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: 'Authorization Failed'
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: 'Internal Server Error'
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-KEY: []
definitions:
  investor:
    title: Investor
    type: object
    properties:
      investor_id:
        type: string
      first_name:
        type: string
      email:
        type: string
      phone_number:
        type: string
      last_name:
        type: string
      national_identifier:
        type: string
      address:
        type: string
      registration_date:
        type: string
  borrower:
    title: Borrower
    type: object
    properties:
      borrower_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      phone_number:
        type: string
      national_identifier:
        type: string
      address:
        type: string
      registration_date:
        type: string
        format: date
  loan:
    title: Loan
    type: object
    properties:
      loan_id:
        type: string
      description:
        type: string
      amount:
        type: number
      currency:
        type: string
      borrower_id:
        type: string
      term:
        type: string
      interest_rate:
        type: string
      loan_type:
        type: string
        enum:
          - PERSONAL
          - BUSINESS
      status:
        type: string
      created_date:
        type: string
        format: date
      repayment_plan:
        type: string
      repayment_start_date:
        type: string
        format: date
      projected_repayment_end_date:
        type: string
        format: date
      investors:
        type: array
        items:
          type: string
  server-error:
    title: Server Error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      tracking_id:
        type: string
  generic-error:
    title: Generic Error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
  page-info:
    title: Page Info
    type: object
    properties:
      offset:
        type: number
      limit:
        type: number
      total_records:
        type: number
      sort:
        type: array
        items:
          type: string
  list-investor-response:
    title: List Campaign Response
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/investor'
      page_info:
          $ref: '#/definitions/page-info'
  list-loan-response:
    title: List Campaign Response
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/loan'
      page_info:
          $ref: '#/definitions/page-info'
  list-borrower-response:
    title: List Campaign Response
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/borrower'
      page_info:
          $ref: '#/definitions/page-info'
