swagger: '2.0'
info:
  version: ''
  title: insurance
  description: ''
host: 'localhost:3000'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  X-API-Key:
    name: X-API-Key
    type: apiKey
    in: header
paths:
  '/quotes/{productId}':
    parameters:
      - name: productId
        in: path
        required: true
        type: string
    post:
      operationId: POST_quotes-productId
      summary: Request Quote
      tags:
        - Quotes
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/quote-criteria'
            example:
              coverage_date:
                from: '2018-07-17'
                to: '2018-08-16'
              plan_type: ESSENTIAL
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/quote-details'
          examples:
            application/json:
              quote_id: q123
              product_id: Travel-Insurance-123
              product_description: exercitation magna elit
              premium_currency: SGD
              premium_amount: 200.5
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/quotes/{quoteId}/purchase':
    parameters:
      - name: quoteId
        in: path
        required: true
        type: string
    post:
      operationId: POST_quotes-quoteId-purchase
      summary: Purchase Insurance
      tags:
        - Quotes
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/purchase-details'
            example:
              quote_reference: nulla Excepteur in do
              personal_details:
                name: reprehenderit id veniam
                email: sint culpa
                date_of_birth: '3435-03-18'
                mobile_phone: incididunt enim aliquip
                national_id: exercitation quis ut
                occupation: sint
                mailing_address: pariatur irure
              payment_details:
                bank_account_id: eiusmod et
                bank_account_number: eiusmod deserunt officia est
                bank_code: culpa incididunt
              travel_details:
                flight_details:
                  departure_flight:
                    flight_no: irure Lorem Duis
                    flight_date: '2218-06-17'
                  return_flight:
                    flight_no: sint labo
                    flight_date: '3419-02-08'
                destination_country: aute Ut
                trip_type: reprehenderit tempor culpa
                coverage_type: ullamco id
                plan_type: dolore sit culpa Ut
                number_of_adults: -3567510
                number_of_children: 72016015
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/invoice'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/policies/{policyId}':
    parameters:
      - name: policyId
        in: path
        required: true
        type: string
    get:
      operationId: GET_policies-policyId
      summary: Get Policy Details
      tags:
        - Policies
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/policy-details'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/claims/policies/{policyId}':
    parameters:
      - name: policyId
        in: path
        required: true
        type: string
    post:
      operationId: POST_claims-policies-policyId
      summary: Claim Insurance
      tags:
        - Claims
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/claim-details'
            example:
              policy_number: 1111-2222-3333
              claimant:
                name: Oscar
                id_type: NRIC
                id: 123-456
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/claim-settlement'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/products/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET-product
      summary: Get Product
      tags:
        - Products
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
    put:
      operationId: PUT-product
      summary: Update Product
      tags:
        - Products
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/product'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
    delete:
      operationId: DELETE-product
      summary: Delete Product
      tags:
        - Products
      responses:
        '204':
          description: ''
      security:
        - Authorization: []
        - X-API-Key: []
  /products:
    get:
      operationId: LIST-products
      summary: List Products
      tags:
        - Products
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
    post:
      operationId: POST-product
      summary: Create Product
      tags:
        - Products
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/product'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
definitions:
  generic-error:
    title: generic-error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
  server-error:
    title: server-error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      tracking_id:
        type: string
  premium-details:
    title: Premium Details
    type: object
    properties:
      currency:
        type: string
      premium_amt:
        type: number
      less_discount:
        type: number
      premium_amt_before_tax:
        type: number
      tax_amt:
        type: number
      total_amt:
        type: number
  coverage-date:
    title: Coverage Date
    type: object
    properties:
      from:
        type: string
        format: date
      to:
        type: string
        format: date
  billing-address:
    title: Billing Address
    type: object
    properties:
      name:
        type: string
      mailing_address:
        type: string
  invoice-details:
    title: Invoice Details
    type: object
    properties:
      provider_id:
        type: string
      provider_name:
        type: string
      policy_id:
        type: string
      product_id:
        type: string
      product_description:
        type: string
      invoice_date:
        type: string
        format: date
      premium_details:
        $ref: '#/definitions/premium-details'
      coverage_date:
        $ref: '#/definitions/coverage-date'
      bill_to:
        $ref: '#/definitions/billing-address'
  policy-holder:
    title: Policy Holder
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      date_of_birth:
        type: string
        format: date
      mobile_phone:
        type: string
      national_id:
        type: string
      occupation:
        type: string
      mailing_address:
        type: string
  flight-schedule:
    title: Flight Schedule
    type: object
    properties:
      flight_no:
        type: string
      flight_date:
        type: string
        format: date
  flight-details:
    title: Flight Details
    type: object
    properties:
      departure_flight:
        $ref: '#/definitions/flight-schedule'
      return_flight:
        $ref: '#/definitions/flight-schedule'
  travel-details:
    title: Travel Details
    type: object
    properties:
      flight_details:
        $ref: '#/definitions/flight-details'
      destination_country:
        type: string
      trip_type:
        type: string
      coverage_type:
        type: string
      plan_type:
        type: string
      number_of_adults:
        type: integer
      number_of_children:
        type: integer
  travel-loss-details:
    title: Travel Loss Details
    type: object
    properties:
      trip_start_date:
        type: string
      trip_end_date:
        type: string
      accident_types:
        type: array
        items:
          type: string
  accident-injury-details:
    title: Accident Injury Details
    type: object
    properties:
      date_of_accident:
        type: string
      time_of_accident:
        type: string
        format: date
      accident_types:
        type: array
        items:
          type: string
      is_injured_same_part_before:
        type: boolean
      is_job_related_injury:
        type: boolean
      description_of_accident:
        type: string
      description_of_injury_sustained:
        type: string
  policy-benefit:
    title: Policy Benefit
    type: object
    properties:
      name:
        type: string
      description:
        type: string
  criteria:
    title: Criteria
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      data_type:
        type: string
  quote-details:
    title: Quote Details
    type: object
    properties:
      quote_id:
        type: string
      product_id:
        type: string
      product_description:
        type: string
      premium_currency:
        type: string
      premium_amount:
        type: number
      number_of_days_covered:
        type: integer
      coverage_dates:
        $ref: '#/definitions/coverage-date'
      add_ons:
        type: array
        items:
          $ref: '#/definitions/product'
  policy-details:
    title: Policy Details
    type: object
    properties:
      policy_id:
        type: string
      product_id:
        type: string
      product_description:
        type: string
      premium_currency:
        type: string
      premium_amount:
        type: number
      policy_holder:
        $ref: '#/definitions/policy-holder'
      benefits:
        type: array
        items:
          $ref: '#/definitions/policy-benefit'
    example:
      policy_id: nisi do
      product_id: id dolore in ut
      product_description: mollit est cupidatat
      premium_currency: culpa et ea
      premium_amount: 95088515
      policy_holder:
        name: aute
        email: consectetur
        date_of_birth: '3355-10-21'
        mobile_phone: 'amet '
        national_id: ex cupidatat
        occupation: elit sunt amet cillum mollit
        mailing_address: id
      benefits:
        - {}
        - description: nostrud velit sint laborum
        - {}
        - description: elit dolore molli
  search-criteria:
    title: Search Criteria
    type: object
    properties:
      criteria:
        type: array
        items:
          $ref: '#/definitions/criteria'
  quotes:
    title: Quotes
    type: object
    properties:
      total:
        type: integer
      criteria:
        type: array
        items:
          $ref: '#/definitions/criteria'
      results:
        type: array
        items:
          $ref: '#/definitions/quote-details'
  purchase-details:
    title: Purchase Details
    type: object
    properties:
      quote_reference:
        type: string
      policy_holder:
        $ref: '#/definitions/policy-holder'
      payment_details:
        $ref: '#/definitions/payment-details'
      travel_details:
        $ref: '#/definitions/travel-details'
    example:
      quote_reference: consectetur
      coverage_start_date: '3582-10-14'
      coverage_end_date: '2618-08-17'
      promotional_discount: -69615412
      quoted_premium: -18097118
      personal_details:
        name: eiusmod in proident
        email: enim adipisicing ipsum
        date_of_birth: '4040-02-17'
        mobile_phone: in fugiat qui
        national_id: ullamco consectetur qui
        occupation: in consequat
        mailing_address: cillum
      payment_details:
        bank_account_id: voluptate reprehenderit nulla mollit cul
        bank_account_number: elit labore
        bank_code: dolore consectetur
      travel_details:
        flight_details:
          departure_flight:
            flight_no: exe
            flight_date: '3488-01-23'
          return_flight:
            flight_no: labore ullamco
            flight_date: '4711-03-03'
        destination_country: minim
        trip_type: sed cillum pariatur velit
        coverage_type: reprehenderit
        plan_type: ipsum et
        number_of_adults: -35038491
        number_of_children: -31630241
  invoice:
    title: Invoice
    type: object
    properties:
      reference_number:
        type: string
      tax_invoice:
        $ref: '#/definitions/invoice-details'
  claim-details:
    title: Claim Details
    type: object
    properties:
      travel_loss_details:
        $ref: '#/definitions/travel-loss-details'
      accident_injury_details:
        $ref: '#/definitions/accident-injury-details'
      total_amount_claimed:
        type: number
      amount_currency:
        type: string
  claim-settlement:
    title: Claim Settlement
    type: object
    properties:
      id:
        type: string
      reference_Id:
        type: string
      policy_id:
        type: string
      approved_amount:
        type: number
      approved_currency:
        type: string
      settlement_date:
        type: string
        format: date
  product:
    title: Product
    type: object
    properties:
      id:
        type: string
      product_name:
        type: string
      product_description:
        type: string
      price_currency:
        type: string
      price_amount:
        type: number
  quote-criteria:
    title: Quote Criteria
    type: object
    properties:
      coverage_date:
        $ref: '#/definitions/coverage-date'
      add_ons:
        type: array
        items:
          $ref: '#/definitions/product'
    example:
      coverage_date:
        from: '2958-07-31'
        to: '2785-02-04'
      add_ons:
        - {}
        - product_description: 'in culpa esse fugiat '
          premium_amount: -33816966
        - premium_amount: 12032198
          product_name: incididunt non minim magna amet
        - {}
        - premium_currency: minim eli
          id: esse consequat culpa
  payment-details:
    title: Payment Details
    type: object
    properties:
      bank_account_id:
        type: string
      bank_account_number:
        type: string
      bank_code:
        type: string