swagger: '2.0'
info:
  version: ''
  title: insurance
  description: ''
host: 'localhost:3000'
basePath: /api
schemes:
  - http
securityDefinitions:
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  X-API-Key:
    name: X-API-Key
    type: apiKey
    in: header
paths:
  '/products/{productId}/buy':
    parameters:
      - name: productId
        in: path
        required: true
        type: string
    post:
      operationId: POST_products-productId-buy
      summary: Buy Insurance
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              quote_id:
                type: string
              coverage_start_date:
                type: string
              coverage_end_date:
                type: string
              promotional_discount:
                type: number
              quoted_premium:
                type: number
              personal_details:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  date_of_birth:
                    type: string
                  mobile_phone:
                    type: string
                  national_id:
                    type: string
                  occupation:
                    type: string
                  mailing_address:
                    type: object
                    properties:
                      unit_no:
                        type: string
                      postal_code:
                        type: string
                      block_no:
                        type: string
                      street_name:
                        type: string
                      building_name:
                        type: string
              travel_details:
                type: object
                properties:
                  flight_details:
                    type: object
                    properties:
                      departure_flight:
                        type: object
                        properties:
                          flight_no:
                            type: string
                          flight_date:
                            type: string
                      return_flight:
                        type: object
                        properties:
                          flight_no:
                            type: string
                          flight_date:
                            type: string
                  destination_country:
                    type: string
                  trip_type:
                    type: string
                  coverage_type:
                    type: string
                  plan_type:
                    type: string
                  number_of_adults:
                    type: integer
                  number_of_children:
                    type: integer
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              reference_number:
                type: string
              tax_invoice:
                type: object
                properties:
                  provider_id:
                    type: string
                  provider_name:
                    type: string
                  policy_id:
                    type: string
                  product_id:
                    type: string
                  product_description:
                    type: string
                  invoice_date:
                    type: string
                  premium_details:
                    type: object
                    properties:
                      currency:
                        type: string
                      premium_amt:
                        type: string
                      less_discount:
                        type: number
                      premium_amt_before_tax:
                        type: number
                      tax_amt:
                        type: number
                      total_amt:
                        type: number
                  coverage_date:
                    type: object
                    properties:
                      from:
                        type: string
                      to:
                        type: string
                  bill_to:
                    type: object
                    properties:
                      name:
                        type: string
                      mailing_address:
                        type: object
                        properties:
                          unit_no:
                            type: string
                          postal_code:
                            type: string
                          block_no:
                            type: string
                          street_name:
                            type: string
                          building_name:
                            type: string
      security:
        - Authorization: []
        - X-API-Key: []
  '/claims/policies/{policyId}':
    parameters:
      - name: policyId
        in: path
        required: true
        type: string
    post:
      operationId: POST_claims-policies-policyId
      summary: Claim Insurance
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              travel_loss_details:
                type: object
                description: Section for Travel Insurance
                properties:
                  trip_start_date:
                    type: string
                  trip_end_date:
                    type: string
                  accident_types:
                    type: array
                    items:
                      type: string
              accident_injury_details:
                type: object
                description: Section for Personal Accident Insurance
                properties:
                  date_of_accident:
                    type: string
                  time_of_accident:
                    type: string
                  accident_types:
                    type: array
                    items:
                      type: string
                  is_injured_same_part_before:
                    type: boolean
                  is_job_related_injury:
                    type: boolean
                  description_of_accident:
                    type: string
                  description_of_injury_sustained:
                    type: string
              total_amount_claimed:
                type: number
            example:
              policy_number: 1111-2222-3333
              claimant:
                name: Oscar
                id_type: NRIC
                id: 123-456
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              reference_Id:
                type: string
              policy_id:
                type: string
              provider_id:
                type: string
              approved_amount:
                type: number
              approved_currency:
                type: string
      security:
        - Authorization: []
        - X-API-Key: []
  '/policies/{policyId}':
    parameters:
      - name: policyId
        in: path
        required: true
        type: string
    get:
      operationId: GET_policies-policyId
      summary: Get Policy Details
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              policy_id:
                type: string
              product_id:
                type: string
              product_description:
                type: string
              premium_currency:
                type: string
              premium_amount:
                type: number
              features:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                  required:
                    - name
                    - description
            required:
              - product_id
              - product_description
      security:
        - Authorization: []
        - X-API-Key: []
  /quotes:
    post:
      operationId: POST_quotes
      summary: Get Quotes
      parameters:
        - name: limit
          in: query
          description: The maximum number of results
          type: number
        - name: sort
          in: query
          description: Sort  results by specific fields
          type: string
        - name: body
          in: body
          schema:
            type: object
            properties:
              criteria:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    data_type:
                      type: string
            example:
              criteria:
                - {}
                - data_type: magna
                - data_type: amet nisi
                  value: dolore irure sit est exercitation
                - name: i
                  value: eu in nisi velit anim
                - {}
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              total:
                type: integer
              criteria:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    data_type:
                      type: string
              results:
                type: array
                items:
                  type: object
                  properties:
                    quote_id:
                      type: string
                    product_id:
                      type: string
                    product_description:
                      type: string
                    premium_currency:
                      type: string
                    premium_amount:
                      type: number
            required:
              - total
      security:
        - Authorization: []
        - X-API-Key: []
definitions: {}