swagger: '2.0'
info:
  version: ''
  title: insurance
  description: ''
host: 'localhost:3000'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  X-API-Key:
    name: X-API-Key
    type: apiKey
    in: header
paths:
  '/quotes/{productId}':
    parameters:
      - name: productId
        in: path
        required: true
        type: string
    post:
      operationId: POST_quotes-productId
      summary: Get Quote
      tags:
        - Quotes
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/policy-info'
            example:
              coverage_date:
                from: '2018-07-17'
                to: '2018-08-16'
              plan_type: ESSENTIAL
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/quote-details'
          examples:
            application/json:
              quote_id: q123
              product_id: Travel-Insurance-123
              product_description: exercitation magna elit
              premium_currency: SGD
              premium_amount: 200.5
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/policies/{policyId}':
    parameters:
      - name: policyId
        in: path
        required: true
        type: string
    get:
      operationId: GET_policies-policyId
      summary: Get Policy Details
      tags:
        - Policies
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/policy-details'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '404':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/claims/policies/{policyId}':
    parameters:
      - name: policyId
        in: path
        required: true
        type: string
    post:
      operationId: POST_claims-policies-policyId
      summary: Claim Insurance
      tags:
        - Claims
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/claim-details'
            example:
              policy_number: 1111-2222-3333
              claimant:
                name: Oscar
                id_type: NRIC
                id: 123-456
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/claim-response'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
  '/products/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET-product
      summary: Get Product
      tags:
        - Products
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
    put:
      operationId: PUT-product
      summary: Update Product
      tags:
        - Products
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/product'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
    delete:
      operationId: DELETE-product
      summary: Delete Product
      tags:
        - Products
      responses:
        '204':
          description: ''
      security:
        - Authorization: []
        - X-API-Key: []
  /products:
    get:
      operationId: LIST-products
      summary: List Products
      tags:
        - Products
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
    post:
      operationId: POST-product
      summary: Create Product
      tags:
        - Products
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/product'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/product'
      security:
        - Authorization: []
        - X-API-Key: []
  '/products/{productId}/buy':
    parameters:
      - name: productId
        in: path
        required: true
        type: string
    post:
      operationId: POST_products-productId-buy
      summary: Buy Insurance
      tags:
        - Products
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/buyer-specifications'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/invoice'
        '400':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '403':
          description: ''
          schema:
            $ref: '#/definitions/generic-error'
        '500':
          description: ''
          schema:
            $ref: '#/definitions/server-error'
      security:
        - Authorization: []
        - X-API-Key: []
definitions:
  premium-details:
    title: Premium Details
    type: object
    properties:
      currency:
        type: string
      premium_amt:
        type: number
      less_discount:
        type: number
      premium_amt_before_tax:
        type: number
      tax_amt:
        type: number
      total_amt:
        type: number
  coverage-date:
    title: Coverage Date
    type: object
    properties:
      from:
        type: string
        format: date
      to:
        type: string
        format: date
  billing-address:
    title: Billing Address
    type: object
    properties:
      name:
        type: string
      mailing_address:
        type: string
  invoice-details:
    title: Invoice Details
    type: object
    properties:
      provider_id:
        type: string
      provider_name:
        type: string
      policy_id:
        type: string
      product_id:
        type: string
      product_description:
        type: string
      invoice_date:
        type: string
        format: date
      premium_details:
        $ref: '#/definitions/premium-details'
      coverage_date:
        $ref: '#/definitions/coverage-date'
      bill_to:
        $ref: '#/definitions/billing-address'
  personal-details:
    title: Personal Details
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      date_of_birth:
        type: string
        format: date
      mobile_phone:
        type: string
      national_id:
        type: string
      occupation:
        type: string
      mailing_address:
        type: string
  flight-schedule:
    title: Flight Schedule
    type: object
    properties:
      flight_no:
        type: string
      flight_date:
        type: string
        format: date
  flight-details:
    title: Flight Details
    type: object
    properties:
      departure_flight:
        $ref: '#/definitions/flight-schedule'
      return_flight:
        $ref: '#/definitions/flight-schedule'
  travel-details:
    title: Travel Details
    type: object
    properties:
      flight_details:
        $ref: '#/definitions/flight-details'
      destination_country:
        type: string
      trip_type:
        type: string
      coverage_type:
        type: string
      plan_type:
        type: string
      number_of_adults:
        type: integer
      number_of_children:
        type: integer
  travel-loss-details:
    title: Travel Loss Details
    type: object
    properties:
      trip_start_date:
        type: string
      trip_end_date:
        type: string
      accident_types:
        type: array
        items:
          type: string
  accident-injury-details:
    title: Accident Injury Details
    type: object
    properties:
      date_of_accident:
        type: string
      time_of_accident:
        type: string
        format: date
      accident_types:
        type: array
        items:
          type: string
      is_injured_same_part_before:
        type: boolean
      is_job_related_injury:
        type: boolean
      description_of_accident:
        type: string
      description_of_injury_sustained:
        type: string
  policy-feature:
    title: Policy Feature
    type: object
    properties:
      name:
        type: string
      description:
        type: string
  criteria:
    title: Criteria
    type: object
    properties:
      name:
        type: string
      value:
        type: string
      data_type:
        type: string
  quote-details:
    title: Quote Details
    type: object
    properties:
      quote_id:
        type: string
      product_id:
        type: string
      product_description:
        type: string
      premium_currency:
        type: string
      premium_amount:
        type: number
  policy-details:
    title: Policy Details
    type: object
    properties:
      policy_id:
        type: string
      product_id:
        type: string
      product_description:
        type: string
      premium_currency:
        type: string
      premium_amount:
        type: number
      features:
        type: array
        items:
          $ref: '#/definitions/policy-feature'
  search-criteria:
    title: Search Criteria
    type: object
    properties:
      criteria:
        type: array
        items:
          $ref: '#/definitions/criteria'
  quotes:
    title: Quotes
    type: object
    properties:
      total:
        type: integer
      criteria:
        type: array
        items:
          $ref: '#/definitions/criteria'
      results:
        type: array
        items:
          $ref: '#/definitions/quote-details'
  buyer-specifications:
    title: Buyer Specifications
    type: object
    properties:
      quote_id:
        type: string
      coverage_start_date:
        type: string
        format: date
      coverage_end_date:
        type: string
        format: date
      promotional_discount:
        type: number
      quoted_premium:
        type: number
      personal_details:
        $ref: '#/definitions/personal-details'
      travel_details:
        $ref: '#/definitions/travel-details'
  invoice:
    title: Invoice
    type: object
    properties:
      reference_number:
        type: string
      tax_invoice:
        $ref: '#/definitions/invoice-details'
  claim-details:
    title: Claim Details
    type: object
    properties:
      travel_loss_details:
        $ref: '#/definitions/travel-loss-details'
      accident_injury_details:
        $ref: '#/definitions/accident-injury-details'
      total_amount_claimed:
        type: number
  claim-response:
    title: Claim Response
    type: object
    properties:
      reference_Id:
        type: string
      policy_id:
        type: string
      provider_id:
        type: string
      approved_amount:
        type: number
      approved_currency:
        type: string
  generic-error:
    title: generic-error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
  server-error:
    title: server-error
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      tracking_id:
        type: string
  product:
    title: Product
    type: object
    properties:
      id:
        type: string
      product_name:
        type: string
      product_description:
        type: string
      premium_currency:
        type: string
      premium_amount:
        type: number
  policy-info:
    title: Policy Info
    type: object
    properties:
      coverage_date:
        $ref: '#/definitions/coverage-date'
      plan_type:
        type: string
        enum:
          - ESSENTIAL
          - COMPREHENSIVE