server:
  port: 9097

spring:
  data:
    mongodb:
#      uri: mongodb+srv://zuhlke01:f10zuhlke@zuhlke-0-pcykf.gcp.mongodb.net/crowd-lending?retryWrites=true
      uri: mongodb://zuhlke01:f10zuhlke@mongodb-container:27017/crowd-lending

