server:
  port: 9091

spring:
  application:
    name: insurance
  data:
    mongodb:
      uri: mongodb+srv://zuhlke01:f10zuhlke@zuhlke-0-pcykf.gcp.mongodb.net/insurance?retryWrites=true

api:
  bank:
    url: http://localhost:9090

payee:
  account:
    number: 333-444-555
    name: "Zuhlke Insurance"
    currency: SGD
